version: '3.1'
services:
  db:
    image: postgres:latest
    container_name: vagas
    restart: always
    environment:
      POSTGRES_DB: vagas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--locale=pt_BR.UTF-8"
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: